# Generated by Django 5.1.4 on 2025-01-13 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonApp', '0002_alter_item_storage_item_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_storage_car',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=50)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_img', models.CharField(max_length=5000)),
            ],
        ),
    ]
