# Generated by Django 5.1.4 on 2025-01-13 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessonApp', '0003_item_storage_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_storage_car',
            name='item_price',
        ),
    ]
