# Generated by Django 5.1.4 on 2025-01-13 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonApp', '0004_remove_item_storage_car_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_storage',
            name='item_img',
            field=models.TextField(),
        ),
    ]
