# Generated by Django 5.1.4 on 2025-02-24 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonApp', '0005_alter_item_storage_item_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateTimeField()),
                ('place_of_birth', models.CharField(choices=[('KT', 'Kampong Thom'), ('Kep', 'Kep'), ('Kratie', 'Kratie'), ('SR', 'Svay Rieng'), ('Pursat', 'Pursat'), ('Takeo', 'Takeo'), ('Siem Reap', 'Siem Reap'), ('KK', 'Koh Kong'), ('KS', 'Kampong Speu'), ('PP', 'Phnom Penh'), ('BB', 'Battambang'), ('RK', 'Ratanakiri'), ('OM', 'Oddar Meanchey'), ('SH', 'Sihanoukville'), ('Kampot', 'Kampot'), ('Kandal', 'Kandal'), ('PV', 'Prey Veng'), ('MK', 'Mondulkiri'), ('ST', 'Stung Treng'), ('PL', 'Palin')], max_length=255)),
                ('language', models.CharField(choices=[('English', 'English'), ('Khmer', 'Khmer')], max_length=100)),
                ('hobby', models.CharField(choices=[('Swimming', 'Swimming'), ('Reading', 'Reading'), ('Bike', 'Bike'), ('Others', 'Others')], max_length=100)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
