# Generated by Django 5.1.4 on 2025-02-24 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonApp', '0006_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
