# Generated by Django 5.1.4 on 2025-03-02 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonApp', '0008_customer_order_supplier_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branchNo', models.CharField(default='Unknown_No', max_length=50, primary_key=True, serialize=False)),
                ('branchAddress', models.CharField(default='N/A', max_length=150)),
                ('telNo', models.CharField(default='N/A', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='staff',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='hobby',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='id',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='language',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='place_of_birth',
        ),
        migrations.AddField(
            model_name='staff',
            name='position',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='staff',
            name='staffNo',
            field=models.CharField(default='anonymous_No', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(default='anonymous', max_length=100),
        ),
        migrations.AddField(
            model_name='staff',
            name='branchNo',
            field=models.ForeignKey(default='N/A', on_delete=django.db.models.deletion.CASCADE, related_name='staff_branch', to='lessonApp.branch'),
        ),
    ]
